# Generated by Django 5.1.3 on 2024-11-23 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Binevoitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("parola", models.CharField(max_length=100)),
                ("nume", models.CharField(max_length=100)),
                ("telefon", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Copil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("varsta", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gen",
                    models.CharField(
                        choices=[("BAIAT", "Baiat"), ("FATA", "Fata")], max_length=10
                    ),
                ),
                ("descriere", models.CharField(blank=True, max_length=1000, null=True)),
                ("parohie", models.CharField(blank=True, max_length=100, null=True)),
                ("daruit", models.BooleanField(default=False)),
                (
                    "binevoitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dvd_app.binevoitor",
                    ),
                ),
            ],
        ),
    ]
