# Generated by Django 5.1.3 on 2024-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dvd_app", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="copil",
            index=models.Index(
                fields=["varsta", "gen"], name="dvd_app_cop_varsta_2c7efe_idx"
            ),
        ),
    ]
