# Generated by Django 5.1.3 on 2024-11-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dvd_app", "0002_copil_dvd_app_cop_varsta_2c7efe_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copil",
            name="descriere",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="copil",
            name="parohie",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
