# Generated by Django 5.1.3 on 2024-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dvd_app", "0003_alter_copil_descriere_alter_copil_parohie"),
    ]

    operations = [
        migrations.AddField(
            model_name="binevoitor",
            name="password_change_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
